# Generated by Django 4.2.10 on 2024-03-02 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='warehouse',
        ),
    ]
