# Generated by Django 4.2.10 on 2024-03-03 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_order_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='warehouse',
        ),
    ]
